### ISSUE TITLE
Descartes package naming

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#12]
Currently, all source/include files are include in the `descartes_trajectory_planning` package.  I would like to propose a new package hierarchy to minimize dependencies and keep things better organized.
- descartes (repo)
  - descartes_core - All abstract and generalize-able classes, common utilities.  Basic implementations can be stored here until interfaces become defined (I'm thinking about the planner here).  This would basically be a rename of `descartes_trajectory_planning`.
  - descartes_moveit - This package would introduce a dependency on moveit.  Wrappers and class implementations that are moveit specific will be stored here.
  - descartes_gui - future - Common GUI tools for editing/managing paths, trajectory planning tools, etc..
  - descartes_planners - future - Specific implementation of planners

NOTE - we should also change namespaces to be identical to package names (this is the ROS convention).

**Comment by shaun-edwards** [comment]
@jrgnicho & @dpsolomon, care to comment

**Comment by jrgnicho** [comment]
Agreed, It's very likely that we'll have to rely on some parts of moveit at some point, thus separating the interfaces from the possible moveit dependent specializations is good forward thinking.  This will be specially useful if we end up having to implement a RobotModel subclass as a wrapper to moveit RobotState. I've already started working with the descartes types so we should address this renaming soon in order to make the transition to these new package names least painful.

**Comment by shaun-edwards** [comment]
Fixed in #19
