### ISSUE TITLE
Waypoints must support joint/cart types

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#3]
The current waypoint types are specific to Cartesian waypoints.  While the majority of a path is expected to be this type, joint waypoints, and other cooler waypoints we don't even know about, should be supported.  To support both joint and Cartesian waypoints, a common base class/interface is proposed.  Specific joint and Cartesian implementations will be created, while still allowing for new, custom types as well.

**Comment by dpsolomon** [comment]
+1 I will take a look at this and maybe make a first pass. If someone else does it first, that would be fine as well.

**Comment by dpsolomon** [comment]
This structure is not developed enough to either limit or promote this idea, but I have one option. The ProcessPt (or WayPoint as it may become in the near future) holds information about the different frames the robot cares about.  We could/should also add a vector of joint positions that satisfy the listed frames, and a function pointer to a "sampler" for that point.  The call to the sampler should populate and/or add to the list of allowable joint positions.

For a fixed joint point, the joint position vector can be fixed to size 1, and the sampler always returns immediately with the fixed point. Alternatively, the sampler does nothing and the joint position is fixed by some other method.

In either case, each WayPoint should be aware of its position in both Cartesian and Joint space at all times, because the use cases will always care about at least one, and most will care about both of these.

The Cartesian position is subtly important whether the point is a fixed joint position of not; When performing Cartesian (including circular) interpolation between points, it must be known what endpoint is being interpolated. Therefore, it is not enough to know that a point is fixed in joint space, but what tool point is being referenced for the path planning task.

Summary:
- Add variable for vector of joint positions that satisfy WayPoint.
- Add pointer to sampler.
- Add funtion to set fixed joint position.
- Add function to update frames based on fixed joint position.

**Comment by dpsolomon** [comment]
Another thought as I submit the last comment:
The ProcessPt was meant to be independant of the robot that is executing the task. There should be another layer that asembles the graph of solutions, and that is probably the appropriate place for a fixed joint point. Perhaps the fixed joint point is a derived class of the ProcessPt?

**Comment by shaun-edwards** [comment]
I found something in openrave that could be just what we are looking for (too bad the website is down).

The openrave [trajectory](https://github.com/rdiankov/openrave/blob/master/include/openrave/trajectory.h) contains waypoints in the form of [configurations](https://github.com/rdiankov/openrave/blob/master/include/openrave/openrave.h#L941).  Configurations contain [groups](https://github.com/rdiankov/openrave/blob/master/include/openrave/openrave.h#L974) (mapped by strings?).

Openrave planners ([google cache](http://webcache.googleusercontent.com/search?q=cache:De2-YRctqDoJ:openrave.org/docs/0.6.6/coreapihtml/arch_planner.html+&cd=1&hl=en&ct=clnk&gl=us)) appear to be similar to MoveIt (i.e. single goal point planners).  

Planning on a trajectory is accomplished via [planning utils](https://github.com/rdiankov/openrave/blob/master/include/openrave/planningutils.h).  These mostly deal with collision avoidance (similar to CLIK).

I'm not familiar with openrave, some things are missing.  It doesn't appear to support tolerances on waypoints, but this may be easily added as a constraint group with a new key name.  It's not clear how these tolerances would be utilized in planning_utils.  

I don't know if our graph based approach will fit into the openrave architecture.  We could leverage the base types (like trajectory and configurations), but there isn't much functionality there.  I think an object oriented approach could result in classes that are more fully defined (instead of the key names approach)..

**Comment by dpsolomon** [comment]
So I started implementing this as follows:
- TrajectoryPtBase
- TrajectoryPtBase <- TrajectoryPtFixedPose
- TrajectoryPtBase <- TrajectoryPtFixedPose <- TrajectoryPtFixedJoint
- TrajectoryPtBase <- TrajectoryPtVariablePose

While this would allow us to build many different classes, it complicates the interface unnecessarily. Now I think we should just do:
- TrajectoryPt
- TrajectoryPt <- TrajectoryPtFixedJoint

A FixedPose is equivalent to a TrajectoryPt with position and orientation tolerances set to 0. The FixedJoint implementation would similarly set those tolerances to 0, and also have a member specifying the joint state for that point.

If anyone thinks we should keep the more complicated interface, let me know. Otherwise, I'm going to go in the simpler direction.  This is a planner in Cartesian space after all, so every point will need all the pertinent Cartesian pose information.

**Comment by shaun-edwards** [comment]
Here were my thoughts (slightly biased by my coding style)
- TrajectoryPtBase
  - Methods
    - bool getCartPose(RobotState, c_pose) ->returns c_pose:Cartesian pose (checks for reach-ability)
    - bool getJointPose(RobotState, j_pose)->returns j_pose: Joint pose (checks for joint limits)
    - bool getJointPoses(RobotState, j_poses)->return j_pose: _all_ Joint poses
    - bool isReachable(RobotState)->obvious
    - id getId() -> returns unique ID for point
    - type getType()-> returns some type info (TBD)

The following classes would inherit from the base class
- JointTrajectoryPt - This class would be constructed with a joint pose.  The RobotState object passed to the methods above would be used to check joint limits and perform FK.
- CartTrajectoryPt - This class would be constructed with a cartesian pose.  The RobotState object passed to the methods above would be used for IK, joint limits.

This approach keeps the robot separate from the waypoint.  The base class interface is all that is required for building a search graph

**Comment by dpsolomon** [comment]
That's fine. I was torn over whether to embed these methods in the pt class
or in a separate sampler object, but I like how this works.

I'll incorporate this and we can flush out the changes as they become more
obvious. For instance, when we sample a pose and get a joint position, do
we also map that to an exact Cartesian  pose, or do we let an external
RobotState take care of that?

Also, I would like to figure out a nice interface for incremental sampling.

**Comment by shaun-edwards** [comment]
I was only considering a nominal Cartesian waypoint (i.e. getPointPoses would return _all_ joint poses at the nominal value - capturing different arm configs/redundant axes).  I'll have to think more about this.

Can you commit the shell of what you are thinking.  We need the call types to do some parallel development on the GUI/graph planner.

I also have some time to commit to this, so feel free to let me some of the work (you direct me).

**Comment by dpsolomon** [comment]
As I implement this, I like it more. I should have at least the shell by
tomorrow night.

**Comment by gavanderhoorn** [comment]
This may be slightly off-topic (for this issue), but for someone who is on the outside of this project, it is unclear whether any existing libraries / platforms were considered. @shaun-edwards mentions OpenRave a few comments earlier: if other libraries were considered, would it be an idea to capture that somewhere?
I kind of like the idea behind MoveIt fi (not necessarily the implementation): using an abstraction layer to allow for the integration of different planner libraries. Has something been considered here as well, or is this is an entirely new effort?

**Comment by shaun-edwards** [comment]
We have looked into other platforms and haven't found anything that directly replicates the functionality we need.  The OpenRave library was the closest thing yet.  MoveIt does have a similar capability, [computeCartesianPath](http://moveit.ros.org/doxygen/classmoveit_1_1planning__interface_1_1MoveGroup.html#ada4a156dc93edc921f15742394475c60), but this does not take into account tolerance zones or perform any sort of search for a plan.  If there is anything out there that does what we need, we aren't aware of it.  

Information like this should be added to a REP.  I've started one [here](https://github.com/ros-industrial/rep/blob/master/rep-I0003.rst), but it's a little out of date.

I like the idea of crating an abstraction layer, but I think this is ambitions for a first revision (even MoveIt had arm_navigation as a precursor).

(EDIT) - If you are aware of anything that does something similar (after reading the REP), I'm interested to learn more.

**Comment by dpsolomon** [comment]
I have my current progress pushed to https://github.com/dpsolomon/descartes/tree/issue%233_trajpt_base_class. I have most of the pure virtual functions actually implemented yet, nd some of them aren't even very clear how they should work across different classes.  I have tried to put class-specific documentation on each of the specific functions, so please read those and comment.

Let me know if you want me to issue a pull request here or flesh this out for a bit first. Another obvious missing item are methods to actually create these points, as there is currently nothing to set the frame/joint data.

**Comment by shaun-edwards** [comment]
This looks like a good start...there are a couple of items for discussion, but nothing major.  Let's do a PR so we can hash these things out.
