### ISSUE TITLE
Parameter ordering

### ISSUE THREAD

**Issue by shaun-edwards** [ros-industrial-consortium/descartes#9]
The function/method parameter ordering does not conform to the ROS style [guide](http://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Function_Parameter_Ordering).  According to the guide, the parameters must be inputs first, outputs last.  Inputs should be passed as const references/points and outputs as non-const.

Affected files: 
- [x] trajectory_pt.h
- [x] cart_trajectory_pt.h
- [x] joint_trajectory_pt.h

**Comment by jrgnicho** [comment]
Good point on the argument arrangement.  One thing to keep in mind is that passing the RobotState object as a const argument limits the methods that can be called since not all of them have the "const" keyword at the end of each method signature.  If we end up implementing our own Robot Model interface, we should make sure that the "const" attribute is adequately applied where needed.
